### PR TITLE
Added remaining snip20 queries

### PR DESCRIPTION
**Pull request by FloppyDisck**
Added remaining queries found on https://github.com/enigmampc/snip20-reference-impl

### CODE REVIEW

**Comment by reuvenpo** [comment]
Thank you for the PR @FloppyDisck !
Have you checked this against a live SNIP-21/22 contract from the latest reference, in a local testnet? just to make sure that it's all working as expected?

**Comment by reuvenpo** [comment]
Also, we already have this functionality included in #23 So I might reject this PR in favor of the other one. I still need to review and compare both.

**Comment by FloppyDisck** [comment]
@reuvenpo Ive tested it in a local testnet, but I can setup a script if needed.

I dont mind which PR gets accepted, as long as the queries are there 👍

**Comment by reuvenpo** [comment]
I'm merging this PR to a canonical branch so that i can fix it up and merge it to master. Thanks for the contribution!

**Pull request merged**
